export { HomeBanner } from './home/homeBanner/HomeBanner'
export { HomeNews } from "./home/homeNews/HomeNews"
export { HomeAds } from "./home/homeAds/HomeAds"
export { HomeProject } from "./home/homeProject/HomeProject"
export { HomeKgPortal } from "./home/homeKgPortal/HomeKgPortal"
export { NewsContend } from "./news/newsContend/NewsContend"
export { Projects } from "./ptojects/Projects"
export { AboutSaitBar } from "./about/aboutSaitBar/AboutSaitBar"
export { AboutContend } from "./about/aboutContent/AboutContend"
export { Admins } from "./admins/Admins"
export {Scroll} from "./scroll/Scroll"
export { Gallery } from "./gallery/Gallery"
export {NewsDeteil} from "./news/newsDeteil/NewsDeteil"
export {ProjectDeteill} from "./projectDeteill/ProjectDeteill"
export {Ads} from "./ads/Ads"